### ISSUE TITLE
gitdist: Fails for case of ambiguous 'HEAD'

### ISSUE THREAD

**Issue by cgbaker** [TriBITSPub/TriBITS#100]
Warnings from git are not well handled by `gitdist dist-repo-status`. 
For example, 
```
$ git tag HEAD
$ git status
warning: refname 'HEAD' is ambiguous.
warning: refname 'HEAD' is ambiguous.
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
```
will put my repo in a state where git commands issue warnings. 

Some commands, such as the one used to determine the local branch, also result in errors:
```
git  rev-parse --abbrev-ref HEAD
warning: refname 'HEAD' is ambiguous.
error: refname 'HEAD' is ambiguous
```

Then, if I attempt a repo status, the parsing crashes: 
```
$ gitdist dist-repo-status
Traceback (most recent call last):
  File "/usr/local/bin/gitdist", line 994, in <module>
    extraRepoStats = getRepoStats(options)
  File "/usr/local/bin/gitdist", line 873, in getRepoStats
    numCommits = getNumCommitsWrtTrackingBranch(options, trackingBranch, getCmndOutputFunc)
  File "/usr/local/bin/gitdist", line 785, in getNumCommitsWrtTrackingBranch
    numAuthorCommits = int(summaryLine.strip().split()[0].strip())
ValueError: invalid literal for int() with base 10: 'warning:'
```

The workaround, if desirable, is to filter out these lines where possible. I'm preparing a pull request with some changes illustrating some workarounds.

**Comment by bartlettroscoe** [comment]
@cgbaker, what version of Python and git are you using?  I run gitdist on repos all the time that are in a deteched head state and not on tracking branches and it works just fine.

**Comment by bartlettroscoe** [comment]
Okay, I have reproduced this with git 2.1.0:

```
[8vt@u235 VERA (master)]$ cp -r TeuchosWrappersExt TeuchosWrappersExt.copy
[8vt@u235 VERA (master)]$ cd TeuchosWrappersExt.copy/
[8vt@u235 TeuchosWrappersExt.copy (master)]$ git tag HEAD
[8vt@u235 TeuchosWrappersExt.copy (master)]$ git  rev-parse --abbrev-ref HEAD
warning: refname 'HEAD' is ambiguous.
error: refname 'HEAD' is ambiguous
```
I should be able to add a unit test for this strange git repo setup and then apply your fix.

**Comment by cgbaker** [comment]
don't forget to `git tag -d HEAD` :) 

i'm on git 2.4.3

**Comment by bartlettroscoe** [comment]
> don't forget to git tag -d HEAD :) 

Indeed!  'HEAD' is a very bad name for a tag, don't you think :-)

I am surprised that git even allows you to create a new tag called 'HEAD'.  But I guess you could have tags with the name as a branch too.  Check it out:

```
[8vt@u235 VERA (master)]$ cd MPACT/
[8vt@u235 MPACT (master)]$ git tag master HEAD^
[8vt@u235 MPACT (master)]$ git checkout master
warning: refname 'master' is ambiguous.
Already on 'master'
Your branch is up-to-date with 'casl-dev/master'.
```
So while a tag named 'HEAD' never makes sense I don't think, I can see a situation were you could create a branch named 'something' then someone could push a tag named 'something' and then you have an ambiguity.  It looks like git solves the ambiguity in this case by selecting the branch over tag name when they are the same.  No such luck for `git  rev-parse --abbrev-ref <ref>`.  It just dies:

```
[8vt@u235 MPACT (master)]$ git  rev-parse --abbrev-ref master
warning: refname 'master' is ambiguous.
error: refname 'master' is ambiguous
```
I should be able to add a unit test for this strange case and then apply your patch.

Thanks!

**Comment by bartlettroscoe** [comment]
As described in commit 3102a4f, I updated the output to make more obvious what the problem is.  I tested this out with a VERA repo that I did a 'git tag HEAD' in and this is what it produced:

```
----------------------------------------------------------------------------
| ID | Repo Dir           | Branch           | Tracking Branch | C | M | ? |
|----|--------------------|------------------|-----------------|---|---|---|
|  0 | VERA (Base)        | master           | casl-dev/master |   |   |   |
|  1 | TriBITS            | master           | casl-dev/master |   |   |   |
|  2 | Trilinos           | master           | casl-dev/master |   |   |   |
|  3 | TeuchosWrappersExt | master           | casl-dev/master |   |   |   |
|  4 | MAMBA              | master           | casl-dev/master |   |   |   |
|  5 | COBRA-TF           | master           | casl-dev/master |   |   |   |
|  6 | VERAInExt          | master           | casl-dev/master |   |   |   |
|  7 | DataTransferKit    | master           | casl-dev/master |   |   |   |
|  8 | MOOSEExt           | master           | casl-dev/master |   |   |   |
|  9 | MOOSEExt/MOOSE     | master           | casl-dev/master |   |   |   |
| 10 | SCALE              | master           | casl-dev/master |   |   |   |
| 11 | SCALE/Exnihilo     | master           | casl-dev/master |   |   |   |
| 12 | XSTools            | master           | casl-dev/master |   |   |   |
| 13 | MPACT              | <AMBIGUOUS-HEAD> | casl-dev/master |   |   |   |
| 14 | LIMEExt            | master           | casl-dev/master |   |   |   |
| 15 | PSSDriversExt      | master           | casl-dev/master |   |   |   |
| 16 | DakotaExt          | master           | casl-dev/master |   |   |   |
| 17 | DakotaExt/Dakota   | master           | casl-dev/master |   |   |   |
| 18 | VUQDemos           | master           | casl-dev/master |   |   |   |
----------------------------------------------------------------------------
```

See, pretty obvious what the problem is, right?  I think that is better than just leaving it empty.
