### ISSUE TITLE
Simplify definition of extra-build configurations for checkin-test script

### ISSUE THREAD

**Issue by bkochuna** [TriBITSPub/TriBITS#196]
This issue is along the lines of a feature request.

**Motivation**
Presently for extra-build configurations the project developer must define a separate `<CONFIGNAME>.config` file in the build directory where the checkin script is run. This can either be done manually or in a shell script that wraps the `project-checkin-test-config.py`. I think this approach has two drawbacks
- The use of a shell script to wrap the `project-checkin-test-config.py` seems to add an "extra layer" of configuration (e.g. a configuration file for a configuration file). This potentially adds an unnecessary step to setting up an automated checkin script.
  - admittedly the shell script has a use case in checking in for different machines/platforms. But I believe the settings here override what is in `project-checkin-test-config.py`. So a lot can be accomplished without a shell script wrapper, and the use case for this would be primarily limited to configuring check-in for multiple dev machines/environments.
- The other drawback of defining the config files from the command line is that these are not necessarily saved. They could be saved in the project repository, but then there is an added step of copying these to build directory which requires some additional configuration outside of `project-checkin-test-config.py` which again increases the complexity of the process.

**Goal**
Simplify the definition of extra-build configurations.
There could be other ways of accomplishing this, but one way is proposed below.

**Proposed modification**
The proposed way of simplifying the definition of extra-build configurations is to is be able to define the extra-build configurations in `project-checkin-test-config.py` in a manner that is analogous to how the default-builds are defined in this file.

**Example**
The contents of `project-checkin-test-config.py` file in TriBITS are:
```
configuration = {

    # The default command line arguments
    'defaults': {
        '--send-email-to-on-push': 'tribits-checkins@googlegroups.com',
        '--enable-all-packages': 'on',
        '--no-rebase': ''
        },
    # NOTE: The last two options --no-rebase --no-append-test-results ensure
    # that the checkin-test.py script does *not* modify the SHA1s of the local
    # commits when pushing to the master repo.  This is important when git
    # commit SHA1s are snaphsotted into other TriBITS projects, for example,
    # in their <projectDir>/cmake/tribits/ directory.

    'cmake': {

        'common': [
            ],

        'default-builds': [

            # Options for the MPI_DEBUG build.
            ('MPI_DEBUG', [
                '-DTPL_ENABLE_MPI:BOOL=ON',
                '-DCMAKE_BUILD_TYPE:STRING=DEBUG',
                '-DTriBITS_ENABLE_DEBUG:BOOL=ON',
                '-DTriBITS_ENABLE_Fortran:BOOL=ON',
                ]),

            # Options for the SERIAL_RELEASE build.
            ('SERIAL_RELEASE', [
                '-DTPL_ENABLE_MPI:BOOL=OFF',
                '-DCMAKE_BUILD_TYPE:STRING=RELEASE',
                '-DTriBITS_ENABLE_DEBUG:BOOL=OFF',
                ]),

            ], # default-builds

        }, # cmake

    } # configuration
```

For a developer to define extra-build configurations the above  `project-checkin-test-config.py` file would be modified in the following way if one were to define a debug build with Intel compilers
```
configuration = {

    # The default command line arguments
    'defaults': {
        '--send-email-to-on-push': 'tribits-checkins@googlegroups.com',
        '--enable-all-packages': 'on',
        '--no-rebase': ''
        },
    # NOTE: The last two options --no-rebase --no-append-test-results ensure
    # that the checkin-test.py script does *not* modify the SHA1s of the local
    # commits when pushing to the master repo.  This is important when git
    # commit SHA1s are snaphsotted into other TriBITS projects, for example,
    # in their <projectDir>/cmake/tribits/ directory.

    'cmake': {

        'common': [
            ],

        'default-builds': [

            # Options for the MPI_DEBUG build.
            ('MPI_DEBUG', [
                '-DTPL_ENABLE_MPI:BOOL=ON',
                '-DCMAKE_BUILD_TYPE:STRING=DEBUG',
                '-DTriBITS_ENABLE_DEBUG:BOOL=ON',
                '-DTriBITS_ENABLE_Fortran:BOOL=ON',
                ]),

            # Options for the SERIAL_RELEASE build.
            ('SERIAL_RELEASE', [
                '-DTPL_ENABLE_MPI:BOOL=OFF',
                '-DCMAKE_BUILD_TYPE:STRING=RELEASE',
                '-DTriBITS_ENABLE_DEBUG:BOOL=OFF',
                ]),

            ], # default-builds

        'extra-builds': [

            # Options for the INTEL_DEBUG build.
            ('INTEL_DEBUG', [
                '-DCMAKE_BUILD_TYPE:STRING=DEBUG',
                '-DTriBITS_ENABLE_DEBUG:BOOL=ON',
                '-DTriBITS_ENABLE_Fortran:BOOL=ON',
                '-DCMAKE_Fortran_COMPILER=ifort',
                '-DCMAKE_C_COMPILER=icc',
                '-DCMAKE_CXX_COMPILER=icpc',
                ]),

            ], # extra-builds

        }, # cmake

    } # configuration
```

**Current Behavior**
For a directory structure like:
- `<PROJECT>`
  - `project-checkin-test-config.py`
  - `checkin-test.py`
- `BUILD`
  - `CHECKIN`

If the checkin.py script is run:
```
[~/BUILD/CHECKIN]$ ../../checkin-test.py --do-all --extra-builds=INTEL_DEBUG
```

The script would output an error like:
```
**************************************************************************
Script: checkin-test.py \
  --src-dir='/home/<USER>/<PROJECT>' \
  --default-builds='MPI_DEBUG,SERIAL_RELEASE' \
  --extra-repos-file='' \
  --extra-repos-type='' \
  --extra-repos='' \
  --require-extra-repos-exist \
  --enable-packages='' \
  --disable-packages='' \
  --enable-all-packages='on'\
  --enable-fwd-packages \
  --continue-if-no-updates \
  --continue-if-no-changes-to-push \
  --continue-if-no-enables \
  --extra-cmake-options='' \
  --test-categories='BASIC' \
  --make-options='' \
  --ctest-options='' \
  --ctest-timeout=300 \
  --no-show-all-tests \
  --st-extra-builds='' \
  --extra-builds='INTEL_DEBUG' \
  --send-email-to='USER' \
  --skip-case-send-email \
  --send-build-case-email=always \
  --send-email-for-all \
  --send-email-to-on-push='' \
  --no-force-push \
  --do-push-readiness-check \
  --no-rebase \
  --append-test-results \
  --do-all \

Starting time: <TIME_STAMP>

**********************************************
*** Performing checkin testing of <PROJECT> ***
**********************************************

ciSupportDir = /home/<USER>/<PROJECT>/TriBITS/tribits/ci_support

srcDir = /home/<USER>/<PROJECT>

baseTestDir = /home/<USER>/BUILD/CHECKIN
Traceback (most recent call last):
  File "../../<PROJECT>/checkin-test.py", line 1410, in main
    success = runProjectTestsWithCommandLineArgs(cmndLineArgs, configuration)
  File "../../<PROJECT>/checkin-test.py", line 1256, in runProjectTestsWithCommandLineArgs
    success = checkinTest(tribitsDir, options, configuration)
  File "<CI_SUPPORT_DIR>/CheckinTest.py", line 2050, in checkinTest
    assertExtraBuildConfigFiles(inOptions.extraBuilds)
  File "<CI_SUPPORT_DIR>/CheckinTest.py", line 258, in assertExtraBuildConfigFiles
    +extraBuildConfigFile+" does not exit!")
Exception: Error, the extra build configuration file INTEL_DEBUG.config does not exit!
```

**Expected/Desired Behavior**
The checkin script automagically generates the `INTEL_DEBUG.config` file in `BUILD/CHECKIN` like it does for `SERIAL_RELEASE` and `MPI_DEBUG` and performs all the requested steps for the defined extra build.

**Comment by bartlettroscoe** [comment]
@bkochuna, thanks for the detailed description.  I can see the motivation for this.

However, one of the advantages of using wrapper scripts is the ability to set up envs so that the compilers and MPI work correctly.  For example, at SNL, there are many compilers that you can only use by loading modules.  Therefore, you can't mix GCC and Intel in the same checkin-test.py invocation in the same env.

Therefore, to make this feature generally useful, I think we would also need to address the issue of using different envs for each build.  An idea for addressing that is given at:

* https://docs.google.com/document/d/1WKs8rJhI3037yKGnEVMhIx9dPN7a7uFRM5isdNAhAXI/edit#bookmark=id.ypgoyhne8p6s

which currently states:

"Allow build cases to define a file to source before running a particular build.  This could be done by defining a file `<BUILD_CASE_NAME>.env.sh` that would be sourced before running a slave python script that does the build/test. This would allow people to run many different types of compilers, etc. all driven with a single invocation of the checkin-test.py script. This script could be sourced and call checkin-test.py as a slave process (which will be added to run builds in parallel, see above).  This could also be incorporated into the project-checkin-test-config.py file by allowing a field for pointing to an existing shell script file in the project source tree perhaps."

Recent experience with Trilinos with the [checkin-test-sems.sh](https://github.com/trilinos/Trilinos/wiki/Policies-%7C-Safe-Checkin-Testing) wrapper has really shown the advantages of forcing an env before a developer runs the checkin-test.py script.  A python script really can't set its own env (and attempts to do so are a huge mess).   But using the approach described above, I guess it could.

In the short-term, has MPACT considered creating its own env and then using a single `checkin-test.sh` wrapper to enforce that env?  That is essentially what CASL VERA does as well with `checkin-test-vera.sh` and I think it has been very successful.  But if you need more than one env, what is requested in this Issue will not be enough.

**Comment by bkochuna** [comment]
Hi Ross,

Thanks for the thoughtful reply. I agree completely that for this feature to be generally useful, and useful in our specific case we do need to be able to handle multiple dev envs. Our situation sounds similar to SNL in that our dev envs are controlled by environment modules.

As the documented note suggests, I think we have a similar use case where what we would like to do is run a single invocation of the checkin-test.py that will build multiple multiple configurations that may have different dev envs (although we may be able to "merge" these environemnts in the short term).

Additionally, I have also identified as enforcing the correct dev env prior to running the check-in script something that is needed.

We have not yet looked at using a shell script to:
1. enforce the dev env (for multiple platforms)
2. do a single invocation of the python checkin script that tests multiple environments

Is accomplishing these two things possible with a shell script and is the VERA checkin shell script a good example of how to accomplish this?

**Comment by bartlettroscoe** [comment]
> 1.    enforce the dev env (for multiple platforms)

The checkin-test-vers.sh (for CASL VERA) and checkin-tests-sems.sh (for Trilinos) both assert that the correct env is loaded.  In the case of checkin-tests-sems.sh (for Trilinos), it actually purges the env and then loads the correct set of modules from scratch (in a new shell so that it does not impact the outer shell).  That has been shown to be super useful in cutting down on the number of mistakes that people make when running it.  You can see the script at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/sems/checkin-test-sems.sh

We should likely update the CASL VERA checkint-test-vera.sh script as well to actually load the env instead of just checking that it was loaded (and that might be an old env anyway).

> 2.    do a single invocation of the python checkin script that tests multiple environments

You currently can't do this with the checkin-test.py script.  That is the extension that is proposed at:

* https://docs.google.com/document/d/1WKs8rJhI3037yKGnEVMhIx9dPN7a7uFRM5isdNAhAXI/edit#bookmark=id.ypgoyhne8p6s

> Is accomplishing these two things possible with a shell script and is the VERA checkin shell script a good example of how to accomplish this?

No.  As stated above, you can enforce a single env but not multiple envs.  You can hack up a set of scripts to do this but it is not pretty.  You basically have to write individual wrapper scripts for checkin-test.py for each env and then a master checkint-test.py driver script that runs the child wrapper scripts.  If you focus on just running `--do-all --push`, this is pretty easy to do.  But if you need to support more fine-grained use cases, it is nasty.

I can try to get to this with some CASL funding but but it could be a few months.

**Comment by bkochuna** [comment]
Thanks again for the quick reply Ross. I think I can probably figure out how to do what we want with shell script. The multiple dev envs may just have to be something we wait on.

**Comment by bartlettroscoe** [comment]
FYI:

I just developed a more elaborate checkin-test.py wrapper script for Trilinos shown at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/checkin-test-atdm.sh

that runs multiple build cases with different envs and then does an overall status check.  It is not perfect but it is pretty close and did not need any changes to the checkin-test.py script.  If you have a more rigid workflow, then this is even easier and cleaner like I did in the case of:

*   https://github.com/TriBITSPub/TriBITS/blob/master/dev_testing/crf450/checkin-test-crf450-do-all-push.sh

I may pull the trigger on:

* https://docs.google.com/document/d/1WKs8rJhI3037yKGnEVMhIx9dPN7a7uFRM5isdNAhAXI/edit#bookmark=kix.zg3piabk0zgg

soon if this wapper script approach is too much of a burden.
