### ISSUE TITLE
gitdist fails with Python 3.5.2

### ISSUE THREAD

**Issue by bartlettroscoe** [TriBITSPub/TriBITS#201]
A potential user of gitdist found that gitdist fails with Python 3.5.2.  I was able to reproduce the problem they are seeing with:

```
$ module load sems-python/3.5.2

$ python3 /home/vera_env/common_tools/gitdist status

Traceback (most recent call last):
  File "/home/vera_env/common_tools/gitdist", line 1453, in <module>
    + addColorToRepoDir(options.useColor,repoName) )
  File "/home/vera_env/common_tools/gitdist", line 814, in addColorToRepoDir
    return txtbld+txtblu+strIn+txtrst
TypeError: can't concat bytes to str
```

Whatever this is, it must not have gotten fixed as part of the Python 3 update in #119.

**Comment by bartlettroscoe** [comment]
This is resolved in commit 681b0f3.   @jmgate came up with the same solution independently so this should be resolved for him too.

Closing as complete.
