### ISSUE TITLE
TriBITS_gitdist_UnitTests move-to-base-dir tests failing on Travis C

### ISSUE THREAD

**Issue by bartlettroscoe** [TriBITSPub/TriBITS#247]
At some point, test `TriBITS_gitdist_UnitTests` started failing with some of the 'move-to-base-dir' tests failing.   The failing using tests are all related to the 'move-to-base-dir' feature.  The unit test output looks like:

```
..
test_gitdist_move_to_base_dir (__main__.test_gitdist) ... FAIL
test_gitdist_move_to_base_dir_no_dist_gitdist_file (__main__.test_gitdist) ... FAIL
======================================================================
FAIL: test_gitdist_move_to_base_dir (__main__.test_gitdist)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/TriBITSPub/TriBITS/test/python_utils/gitdist_UnitTests.py", line 1554, in test_gitdist_move_to_base_dir
    self.assertEqual(s(cmndOut), s(cmndOut_expected))
AssertionError: "\n*** Base Git Repo: TriBITS\n['mockgit', 'status']\n\n" != "\n*** Base Git Repo: MockProjectDir\n['mockgit', 'status']\n\n*** Git Repo: ExtraRepo\n['mockgit', 'status']\n\n"

======================================================================
FAIL: test_gitdist_move_to_base_dir_no_dist_gitdist_file (__main__.test_gitdist)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/TriBITSPub/TriBITS/test/python_utils/gitdist_UnitTests.py", line 1614, in test_gitdist_move_to_base_dir_no_dist_gitdist_file
    self.assertEqual(s(cmndOut), s(cmndOut_expected))
AssertionError: "\n*** Base Git Repo: TriBITS\n['mockgit', 'status']\n\n" != "\n*** Base Git Repo: somewhere\n['mockgit', 'status']\n\n"

----------------------------------------------------------------------
Ran 53 tests in 2.850s

FAILED (failures=2)
('cmndOut = ', "Error, env var GITDIST_MOVE_TO_BASE_DIR='INVALID' is invalid!  Valid choices include empty '', IMMEDIATE_BASE, and EXTREME_BASE.\n")
('cmndOut_expected = ', "Error, env var GITDIST_MOVE_TO_BASE_DIR='INVALID' is invalid!  Valid choices include empty '', IMMEDIATE_BASE, and EXTREME_BASE.\n")
```

**Comment by bartlettroscoe** [comment]
I bet I know what the problem is.  The Travis CI build creates the build dir under the TriBITS project source dir.  This changes the behavior of the tests since now the base-most `.gitdist.default` file is in the base TriBITS/ source dir, not in the test dir.  Seems like the gitdist command should be given a max depth argument or something to stop gitdist from looking too deep.  But for now, I will just have Travis CI remove the base `TriBITS/.gitdist.default` file and see if that fixes the problem.

**Comment by bartlettroscoe** [comment]
My commit 1ef4e3d just pushed to `master` seems to have fixed this test as shown at:

* https://travis-ci.org/TriBITSPub/TriBITS/builds/325151180
* https://my.cdash.org/index.php?project=TriBITS&parentid=1346030&field1=buildstarttime/date&compare1=84&value1=now

Closing as complete.
